name: Terraform Deployment

on:
  push:
    branches:
      - develop
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch: # Permite disparo manual do workflow

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_NUMBER: ${{ vars.AWS_ACCOUNT_NUMBER }}
  #
  ORGANIZATION: ${{ vars.ORGANIZATION }}
  ACCOUNT: ${{ vars.ACCOUNT }}
  ENVIRONMENT: ${{ vars.ENVIRONMENT }}
  WORKLOAD: ${{ vars.WORKLOAD }}
  MY_VARIABLE: "Hello, World!"

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-24.04
    environment:
      name: develop # Nome do ambiente configurado no GitHub
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./terraform

    steps:
      # 1. Checkout do código
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      # 2. Configurar o Terraform
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Show Variable in Logs
        run: |
          echo "O valor da variável é: $WORKLOAD"

      # # 3. Configurar Credenciais da AWS com Secrets do Environment
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ vars.REGION }} # Variável do Environment

      # - name: Terraform init
      #   id: init
      #   # run: terraform init -backend-config="env/backend_s3_prd.hcl"
      #   run: terraform init \
      #     -backend-config="region=${AWS_REGION}" \
      #     -backend-config="bucket=terraform-state-${AWS_ACCOUNT_NUMBER}-${AWS_REGION}" \
      #     -backend-config="key=${organization}/${account}/${environment}/${value}.tfstate" \
      #     -backend-config="assume_role={role_arn=\"arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/TerraformState\"}"
      #     -backend-config="dynamodb_table=terraform-state" \
      #     -backend-config="encrypt=true" \
      #     -backend-config="kms_key_id=alias/terraform-state"

      # - name: Terraform format
      #   id: fmt
      #   run: terraform fmt -check

      # - name: Terraform validate
      #   id: validate
      #   run: terraform validate


    # strategy:
    #   matrix:
    #     environment: [dev, staging, prod] # Define os ambientes

    # steps:
    #   # 1. Checa o código do repositório
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   # 2. Configura o Terraform
    #   - name: Setup Terraform
    #     uses: hashicorp/setup-terraform@v2
    #     with:
    #       terraform_version: 1.10.0

    #   # 3. Carregar JSON do Secret
    #   - name: Load environment variables from JSON
    #     run: |
    #       echo "${{ secrets['JSON_' + matrix.environment | upper] }}" > env.json
    #       cat env.json # Exibe o JSON para debug (opcional)

    #   # 4. Extrair variáveis do JSON
    #   - name: Parse JSON
    #     id: parse_json
    #     run: |
    #       # Faz o parse de todas as chaves e valores do ambiente atual
    #       jq -r ".${{ matrix.environment }} | to_entries | .[]" config.json | while read entry; do
    #         key=$(echo $entry | jq -r '.key')  # Extrai a chave
    #         value=$(echo $entry | jq -r '.value')  # Extrai o valor
    #         echo "Exportando variável: TF_VAR_${key^^}=$value"
    #         echo "TF_VAR_${key^^}=$value" >> $GITHUB_ENV  # Exporta a variável como global
    #       done
    #     # run: |
    #     #     export REGION=$(jq -r '.region' env.json)
    #     #     export INSTANCE_TYPE=$(jq -r '.instance_type' env.json)
    #     #     echo "TF_VAR_REGION=$REGION" >> $GITHUB_ENV
    #     #     echo "TF_VAR_INSTANCE_TYPE=$INSTANCE_TYPE" >> $GITHUB_ENV

    #   # 5. Inicializar o Terraform
    #   - name: Terraform Init
    #     run: terraform init -backend-config="envs/${{ matrix.environment }}/backend.tfvars"

    #   # 6. Planejar a implantação
    #   - name: Terraform Plan
    #     run: terraform plan
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    #   # 7. Aplicar as mudanças
    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve
    #     env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # #   - name: Terraform Plan
    # #     run: terraform plan
    # #     env:
    # #       TF_VAR_REGION: ${{ secrets['TF_VAR_REGION_' + matrix.environment | upper] }}
    # #       TF_VAR_INSTANCE_TYPE: ${{ secrets['TF_VAR_INSTANCE_TYPE_' + matrix.environment | upper] }}
    # #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    # #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # #   # 5. Aplica as mudanças
    # #   - name: Terraform Apply
    # #     run: terraform apply -auto-approve
    # #     env:
    # #       TF_VAR_REGION: ${{ secrets['TF_VAR_REGION_' + matrix.environment | upper] }}
    # #       TF_VAR_INSTANCE_TYPE: ${{ secrets['TF_VAR_INSTANCE_TYPE_' + matrix.environment | upper] }}
    # #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    # #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
